version: "3.8"
services:
  mongo:
    image: mongo:latest
    # ports:
    # - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:3000"
    depends_on:
      - mongo
    environment:
      PORT: 3000
      CORS_ORIGINS: http://localhost:4321
      MONGO_URI: mongodb://mongo:27017/yourdb
    env_file: ".env"

volumes:
  mongo_data:
